name: Build MasterUI (Linux x64)

on:
  push:
    branches:
      - master
    pull_request:

jobs:
  build-linux:
    name: Compile for linux.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare OS
        run: sudo apt update 
      - name: Install dependencies
        run: sudo apt install openjdk-8-jdk ant -y
      - name: Chmod build.sh
        run: chmod +x .github/build.sh
      - name: Build project
        run: .github/build.sh
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Linux
          path: ./out/artifacts/MasterUI/MasterUI.jar
