name: Build MasterUI (Linux x64)

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  build-linux:
    name: Compile for linux.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare OS
        run: sudo apt update 
      - name: Install dependencies
        run: sudo apt install openjdk-8-jdk ant -y
      - name: Chmod build.sh
        run: chmod +x .github/build.sh
      - name: Build project
        run: .github/build.sh
      - name: Upload Core
        uses: actions/upload-artifact@v4
        with:
          name: MasterUI - Core
          path: ./out/artifacts/core/core.jar
      - name: Upload Renderer: Texel
        uses: actions/upload-artifact@v4
        with:
          name: MasterUI - Texel
          path: ./out/artifacts/texel/texel.jar
